name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitattributes
    - .gitignore
    - .prettierignore
    - CHANGELOG.md
    - LICENSE.md
    - README.md
    - nodemon.json

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        node-version-file: .node-version
    - name: Install dependencies
      run: npm ci
    - name: Check formatting
      run: npm run fmt:check
    - name: Lint code
      run: npm run lint
    - name: Run unit tests
      run: npm run test

  build:
    name: Build
    needs: [ verify ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        node-version-file: .node-version
    - name: Install dependencies
      run: npm ci
    - name: Build Chrome extension
      run: npm run build
    - name: Upload build artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: dist
        path: dist

  release:
    name: Release?
    needs: [ build ]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Prepare a release
      id: release
      uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
      with:
        config-file: .github/release-please-config.json
        manifest-file: .github/release-please-manifest.json
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Download build artifact
      if: ${{ steps.release.outputs.release_created }}
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: dist
        path: dist
    - name: Compress build artefacts
      if: ${{ steps.release.outputs.release_created }}
      run: (cd dist && zip -r ../${{ steps.release.outputs.tag_name }}.zip .)
    - name: Attach build artifact to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ steps.release.outputs.release_created }}
      run: gh release upload ${{ steps.release.outputs.tag_name }} ${{ steps.release.outputs.tag_name }}.zip
    - name: Publish release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ steps.release.outputs.release_created }}
      run: gh release edit ${{ steps.release.outputs.tag_name }} --draft=false
