name: PR

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitattributes
    - .gitignore
    - .prettierignore
    - LICENSE.md
    - README.md
    - nodemon.json

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Check formatting
      run: npm run fmt:check
    - name: Lint code
      run: npm run lint
    - name: Run unit tests
      run: npm test

  build:
    name: Build
    needs: [ verify ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Build Chrome extension
      run: npm run build
