name: Tag

on:
  push:
    tags:
    - v*.*.*

jobs:
  build_chrome_extension:
    name: Build Chrome extension
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Build Chrome extension
      run: npm run build
    - name: Compress Chrome extension
      run: zip -r -FS ./dist/chrome-extension.zip dist

  publish_chrome_extension:
    name: Upload Chrome extension
    needs: [ build_chrome_extension ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: npm
        cache-dependency-path: package-lock.json
        node-version: 20
    - name: Install dependencies
      run: npm ci
